### ISSUE TITLE
Title resturns the media name in front

### ISSUE THREAD

**Issue by jiangcheng1999** [Iceloof/GoogleNews#138]
since weeks ago, you will receive the title with the media name, for instance, if you search 'Tesla' , you would obtain the first result:
{'title': 'CBS NewsMoreViral video of Tesla driver wearing Apple Vision Pro headset raises safety concerns',
 'desc': None,
 'date': '11 hours ago',
 'datetime': datetime.datetime(2024, 2, 5, 22, 59, 16, 329814),
 'link': 'news.google.com/articles/CBMiUmh0dHBzOi8vd3d3LmNic25ld3MuY29tL25ld3MvdGVzbGEtZHJpdmVyLXdlYXJpbmctYXBwbGUtdmlzaW9uLXByby1wZXRlLWJ1dHRpZ2llZy_SAVZodHRwczovL3d3dy5jYnNuZXdzLmNvbS9hbXAvbmV3cy90ZXNsYS1kcml2ZXItd2VhcmluZy1hcHBsZS12aXNpb24tcHJvLXBldGUtYnV0dGlnaWVnLw?hl=en-US&gl=US&ceid=US%3Aen',
 'img': '/api/attachments/CC8iK0NnNVdOalUwTVVKUU4xSlpUalJCVFJDakFSaTJBaWdCTWdZQkVJN01OUVk=-w64-h64-p-df',
 'media': 'CBS News',
 'site': None
 
 which includes the media name in the title, could you fix this issue?

**Comment by jlchen14** [comment]
on the contrary, i think this “mal-function” is good, because I can get
more information apart from the title, the media name appears to be useful
for filtering.

By the way, if you insist on the clear title, you can try:

Title=title.split(“MoreViral”)[1]

then you get the clear title.

best regards

cjl


jiangcheng1999 ***@***.***>于2024年2月6日 周二17:04写道：

**Comment by HurinHu** [comment]
Problem solved in the latest version (1.6.13)
